name: UnitTest checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [ "3.9"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: | 
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Test all
#        run: python -m unittest src/tests_star/test_star_wars.py
#      - name: Test planet
#        run: python -m unittest src/tests_star/test_planet.py
#      - name: Test history
#        run: python -m unittest src/tests_star/test_history.py
#      - name: Test people
#        run: python -m unittest src/tests_star/test_people.py
  mac-os:
    needs: ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-12 ]
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #      - name: Test all
      #        run: python -m unittest src/tests_star/test_star_wars.py
#      - name: Test planet
#        run: python -m unittest src/tests_star/test_planet.py
#      - name: Test history
#        run: python -m unittest src/tests_star/test_history.py
#      - name: Test people
#        run: python -m unittest src/tests_star/test_people.py
  windows:
    needs: mac-os
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022 ]
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if  (-f requirements.txt)  { pip install -r requirements.txt}
      #      - name: Test all
      #        run: python -m unittest src/tests_star/test_star_wars.py
      - name: Test planet
        run: python -m unittest src/tests_star/test_planet.py
      - name: Test history
        run: python -m unittest src/tests_star/test_history.py
      - name: Test people
        run: python -m unittest src/tests_star/test_people.py
